language: objective-c
osx_image: xcode11.2
cache: cocoapods
podfile: Podfile

script:
- set -o pipefail
- xcodebuild -workspace KKProgressToolbar.xcworkspace -scheme KKProgressToolbar -destination 'name=iPhone 8' build CODE_SIGN_IDENTITY="" CODE_SIGNING_ALLOWED=NO | xcpretty
