name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: ${{ matrix.platform }} on ${{ matrix.os }}
    runs-on: macos-latest
    env:
      scheme: APProgressToolbar
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: iPhone 16 Pro
            os: 18.2
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run test on ${{ matrix.platform }} (iOS ${{ matrix.os }})
        run: |
          xcodebuild test \
            -scheme $scheme \
            -destination 'platform=iOS Simulator,name=${{ matrix.platform }},OS=${{ matrix.os }}'

