name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run macOS tests
      run: swift test -v
    - name: Run iOS tests
      run: xcodebuild test  -workspace KKProgressToolbar.xcworkspace -scheme KKProgressToolbar -destination platform="iOS Simulator,name=iPhone 11 Pro"
    - uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: FailedRenderTests
        path: FailedRenderTests
