name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run tests and generate report
        run: xcodebuild test \
          -scheme APProgressToolbar \
          -destination 'platform=iOS Simulator,name=iPhone Air,OS=26.0'
